import STAGES, { STAGE_LIST } from './stages.js';
import { CHARACTER_ROLES, CHARACTER_ROLE_LIST, RELATIONSHIP_TYPES, RELATIONSHIP_TYPE_LIST } from './roles.js';
import { 
  JOB_STATUSES, 
  JOB_STATUS_LIST, 
  DOCUMENT_STATUSES, 
  DOCUMENT_STATUS_LIST,
  CONTINUITY_SEVERITIES,
  CONTINUITY_SEVERITY_LIST,
  CONTINUITY_STATUSES,
  CONTINUITY_STATUS_LIST
} from './job-status.js';

export {
  STAGES,
  STAGE_LIST,
  CHARACTER_ROLES,
  CHARACTER_ROLE_LIST,
  RELATIONSHIP_TYPES,
  RELATIONSHIP_TYPE_LIST,
  JOB_STATUSES,
  JOB_STATUS_LIST,
  DOCUMENT_STATUSES,
  DOCUMENT_STATUS_LIST,
  CONTINUITY_SEVERITIES,
  CONTINUITY_SEVERITY_LIST,
  CONTINUITY_STATUSES,
  CONTINUITY_STATUS_LIST
};
